## This Project is intended to use SQL to answer questions related to Men and Women Branded Perfume.
#### Question 1: Are some Brands more successful than others?
#### Question 2: Which Perfume types sell more.

In [1]:
import duckdb as db

In [2]:
mens = db.read_csv("Data/ebay_mens_perfume.csv").df()
womens= db.read_csv("Data/ebay_womens_perfume.csv").df()
sql = db.sql
mens

,brand,title,type,price,priceWithCurrency,available,availableText,sold,lastUpdated,itemLocation
0,Dior,Christian Dior Sauvage Men's EDP 3.4 oz Fragra...,Eau de Parfum,84.99,US $84.99/ea,10,More than 10 available / 116 sold,116,"May 24, 2024 10:03:04 PDT","Allen Park, Michigan, United States"
1,AS SHOW,A-v-entus Eau de Parfum 3.3 oz 100ML Millesime...,Eau de Parfum,109.99,US $109.99,8,8 available / 48 sold,48,"May 23, 2024 23:07:49 PDT","Atlanta, Georgia, Canada"
2,Unbranded,HOGO BOSS cologne For Men 3.4 oz,Eau de Toilette,100.00,US $100.00,10,More than 10 available / 27 sold,27,"May 22, 2024 21:55:43 PDT","Dearborn, Michigan, United States"
3,Giorgio Armani,Acqua Di Gio by Giorgio Armani 6.7 Fl oz Eau D...,Eau de Toilette,44.99,US $44.99/ea,2,2 available / 159 sold,159,"May 24, 2024 03:30:43 PDT","Reinholds, Pennsylvania, United States"
4,Lattafa,Lattafa Men's Hayaati Al Maleky EDP Spray 3.4 ...,Fragrances,16.91,US $16.91,<NA>,Limited quantity available / 156 sold,156,"May 24, 2024 07:56:25 PDT","Brooklyn, New York, United States"
...,...,...,...,...,...,...,...,...,...,...
995,GUESS,Guess 1981 by Guess cologne for men EDT 3.3 / ...,Eau de Toilette,20.28,US $20.28/ea,45,"45 available / 1,613 sold",1613,"May 24, 2024 08:14:07 PDT","Dallas, Texas, United States"
996,Armaf,Club de Nuit Intense by Armaf cologne for men ...,Eau de Toilette,30.58,US $30.58,10,More than 10 available / 31 sold,31,"May 23, 2024 08:39:30 PDT",United States
997,Paco Rabanne,Invictus by Paco Rabanne for Men EDT Spray 3.4...,Eau de Toilette,39.99,US $39.99/ea,2,2 available / 305 sold,305,"May 23, 2024 15:27:18 PDT","Jamaica, New York, United States"
998,Lomani,"Lomani EDT Cologne 3.4 oz Men - Authentic, Bra...",Eau de Toilette,9.99,US $9.99/ea,2,2 available / 22 sold,22,"May 20, 2024 13:20:54 PDT","Lincoln Park, Michigan, United States"
999,Estee Lauder,Beyond Paradise by Estee Lauder for Men Cologn...,Cologne spray,17.49,US $17.49/ea,10,More than 10 available / 24 sold,24,"Feb 28, 2024 07:27:01 PST","Keyport, New Jersey, United States"

In [3]:
womens

,brand,title,type,price,priceWithCurrency,available,availableText,sold,lastUpdated,itemLocation
0,Carolina Herrera,Good Girl by Carolina Herrera 2.7 oz Eau De Pa...,Eau de Parfum,43.99,US $43.99/ea,2,2 available / 393 sold,393,"May 23, 2024 10:43:50 PDT","Thomasville, Alabama, United States"
1,As Shown,Parfums de Marly Delina La Rosee Eau de Parfum...,Eau de Parfum,79.99,US $79.99,5,5 available / 40 sold,40,"May 24, 2024 00:15:48 PDT","New Jersey, Hong Kong"
2,PRADA,PRADA Paradoxe by Prada EDP 3.0oz/90ml Spray P...,Eau de Parfum,59.99,US $59.99,10,More than 10 available / 35 sold,35,"May 14, 2024 20:54:25 PDT","Orange, New Jersey, United States"
3,As Show,J'adore Parfum D'eau by Christian 3.4 oz EDP F...,Eau de Parfum,59.99,US $59.99/ea,10,More than 10 available / 9 sold,9,"May 23, 2024 01:23:05 PDT","USA, New Jersey, Hong Kong"
4,Khadlaj,Shiyaaka for Men EDP Spray 100ML (3.4 FL.OZ) B...,Eau de Parfum,29.99,US $29.99/ea,10,More than 10 available,<NA>,NaN,"Little Ferry, New Jersey, United States"
...,...,...,...,...,...,...,...,...,...,...
995,Avon,Avon Far Away Infinity Eau de Parfum 1.7 fl. o...,Eau de Parfum,13.89,US $13.89,10,More than 10 available / 157 sold,157,"May 16, 2024 22:35:29 PDT","West Palm Beach, Florida, United States"
996,Mancera,Roses Greedy by Mancera perfume for unisex EDP...,Eau de Parfum,57.85,US $57.85/ea,33,33 available / 58 sold,58,"May 24, 2024 08:03:11 PDT","Dallas, Texas, United States"
997,Unbranded,"Sweet Tooth Eau de Parfum, Perfume for Women, ...",1,30.96,US $30.96,2,2 available / 3 sold,3,"May 17, 2024 23:16:41 PDT","New York, New York, United States"
998,Juliette Has A Gun,MMMM BY Juliette Has A Gun perfume for her EDP...,Eau de Perfume,53.99,US $53.99/ea,3,3 available / 117 sold,117,"May 13, 2024 22:19:34 PDT","Dallas, Texas, United States"
999,Paris Hilton,PARIS HILTON ELECTRIFY for Women Cologne 3.4 o...,Eau de Parfum,14.99,US $14.99/ea,4,4 available / 51 sold,51,"May 22, 2024 05:44:45 PDT","TX, United States"

In [4]:
#lets join these 2 tables and use them together.
sql(""" COPY(
SELECT *
FROM mens
UNION ALL
SELECT *
FROM womens)
TO 'menandwomenperfume.csv' (HEADER, DELIMITER ',');
""")

In [5]:
#lets now add that new table to what we're working with so we don't need to keep unioning.
perfume = db.read_csv("Data/menandwomenperfume.csv").df()

In [6]:
sql("""
SELECT 
    brand,
    SUM(sold) AS total_sold
FROM perfume
WHERE brand IS NOT NULL
GROUP BY brand
ORDER BY total_sold DESC
LIMIT 20;
""").df()

               brand  total_sold
0       Calvin Klein    145672.0
1            Versace    128077.0
2           Davidoff     60289.0
3             Azzaro     38305.0
4           Burberry     38001.0
5      Liz Claiborne     29170.0
6    Dolce & Gabbana     28570.0
7              Armaf     27120.0
8       Kenneth Cole     24636.0
9       Paco Rabanne     23506.0
10      Ralph Lauren     20849.0
11  Elizabeth Taylor     20653.0
12         Vera Wang     20308.0
13       2nd To None     18882.0
14         HUGO BOSS     18811.0
15       Perry Ellis     17279.0
16             Coach     17056.0
17     Dolce&Gabbana     16362.0
18             GUESS     15093.0
19     Juicy Couture     14799.0

In [7]:
#since there are 2 Giorgio Beverly Hills, lets try making everything lowercase for the group by.
sql("""
SELECT 
    LOWER(brand) AS brand,
    SUM(sold) AS total_sold
FROM perfume
WHERE brand IS NOT NULL
GROUP BY LOWER(brand)
ORDER BY total_sold DESC
LIMIT 20;
""").df()

               brand  total_sold
0       calvin klein    145672.0
1            versace    128077.0
2           davidoff     60289.0
3           burberry     38361.0
4             azzaro     38305.0
5      liz claiborne     29170.0
6    dolce & gabbana     28570.0
7              armaf     27120.0
8       kenneth cole     24636.0
9       paco rabanne     23506.0
10      ralph lauren     20849.0
11  elizabeth taylor     20653.0
12         vera wang     20308.0
13         hugo boss     19502.0
14       2nd to none     18882.0
15       perry ellis     17279.0
16             coach     17056.0
17     dolce&gabbana     16362.0
18             guess     15093.0
19     juicy couture     14799.0